We need to make sure that uperf runs on the appropriate system.
redhat-performance/uperf-wrapper pull request #32
Opened 2024-12-05 15:37 UTC by dvalinrh

Before this change we always run uperf on the system we are running the wrapper on. This may not be the case.  To fix this requires a couple things
1) Make sure uperf wrapper is installed on the system we are suppose
   to be running on.
2) ssh to the system and run the wrapper.  Note we pass an extra
   option --spawned, which tells the uperf wrapper it has been spawned
   by another uperf wrapper and not to spawn again.
3) Once complete, we have make sure we have the results on the system
   we originally started from.
4) Handle multiple invocations of uperf on differing systems.

2024-12-10 13:19 UTC, dvalinrh commented on uperf/uperf_run
> +	#
change comment to be targeted client.

2024-12-18 00:40 UTC, frival commented on uperf/uperf_run
> +			scp xml${net_count} root@$client:/root/xml${net_count} > /dev/null
For future-proofing, we need to see if /root will be writeable for bootc-based images.  It's unclear from the Fedora documentation if the root user will still use /root (it references /var/roothome) for its writeable area.

2024-12-18 00:42 UTC, frival commented on uperf/uperf_run
> +	ssh -oStrictHostKeyChecking=no root@$client "pkill -x -9 uperf"
Can you add a comment about why -X is needed so nobody thinks they can be economical in the future and delete it?

2024-12-18 00:43 UTC, frival reviewed
LGTM, just one future warning and a couple of comments requested.  Pop those in and I'll approve.

2025-01-07 19:52 UTC, kdvalin requested changes

2025-01-07 19:52 UTC, kdvalin commented on uperf/uperf_run
> +		# Note: We expext /root to be writeable.  We are unsure at this
```suggestion
		# Note: We expect /root to be writeable.  We are unsure at this
```

2025-01-07 19:52 UTC, kdvalin commented on uperf/uperf_run
> +		# Note: We expext /root to be writeable.  We are unsure at this
Typo

2025-01-14 13:47 UTC, frival approved these changes
LGTM

2025-01-14 13:59 UTC, kdvalin approved these changes
LGTM

2025-01-14 14:00 UTC, merged